# Data Cleaning - Online News Popularity

## Objective
Prepare the dataset for analysis by:
- Loading data
- Checking structure and quality
- Handling unnecessary columns
- Preparing features for SQL and ML

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np

In [13]:
# Load Dataset
df = pd.read_csv("../data/raw/OnlineNewsPopularity.csv")

df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [5]:
# Basic Info
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 61 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            39644 non-null  object
 1   timedelta                      39644 non-null  float64
 2   n_tokens_title                 39644 non-null  float64
 3   n_tokens_content               39644 non-null  float64
 4   n_unique_tokens                39644 non-null  float64
 5   n_non_stop_words               39644 non-null  float64
 6   n_non_stop_unique_tokens       39644 non-null  float64
 7   num_hrefs                      39644 non-null  float64
 8   num_self_hrefs                 39644 non-null  float64
 9   num_imgs                       39644 non-null  float64
 10  num_videos                     39644 non-null  float64
 11  average_token_length           39644 non-null  float64
 12  num_keywords                   39644 non-null  float64
 13  data_channel_is_lifestyle      39644 non-null  float64
 14  data_channel_is_entertainment  39644 non-null  float64
 15  data_channel_is_bus            39644 non-null  float64
 16  data_channel_is_socmed         39644 non-null  float64
 17  data_channel_is_tech           39644 non-null  float64
 18  data_channel_is_world          39644 non-null  float64
 19  kw_min_min                     39644 non-null  float64
 20  kw_max_min                     39644 non-null  float64
 21  kw_avg_min                     39644 non-null  float64
 22  kw_min_max                     39644 non-null  float64
 23  kw_max_max                     39644 non-null  float64
 24  kw_avg_max                     39644 non-null  float64
 25  kw_min_avg                     39644 non-null  float64
 26  kw_max_avg                     39644 non-null  float64
 27  kw_avg_avg                     39644 non-null  float64
 28  self_reference_min_shares      39644 non-null  float64
 29  self_reference_max_shares      39644 non-null  float64
 30  self_reference_avg_sharess     39644 non-null  float64
 31  weekday_is_monday              39644 non-null  float64
 32  weekday_is_tuesday             39644 non-null  float64
 33  weekday_is_wednesday           39644 non-null  float64
 34  weekday_is_thursday            39644 non-null  float64
 35  weekday_is_friday              39644 non-null  float64
 36  weekday_is_saturday            39644 non-null  float64
 37  weekday_is_sunday              39644 non-null  float64
 38  is_weekend                     39644 non-null  float64
 39  LDA_00                         39644 non-null  float64
 40  LDA_01                         39644 non-null  float64
 41  LDA_02                         39644 non-null  float64
 42  LDA_03                         39644 non-null  float64
 43  LDA_04                         39644 non-null  float64
 44  global_subjectivity            39644 non-null  float64
 45  global_sentiment_polarity      39644 non-null  float64
 46  global_rate_positive_words     39644 non-null  float64
 47  global_rate_negative_words     39644 non-null  float64
 48  rate_positive_words            39644 non-null  float64
 49  rate_negative_words            39644 non-null  float64
 50  avg_positive_polarity          39644 non-null  float64
 51  min_positive_polarity          39644 non-null  float64
 52  max_positive_polarity          39644 non-null  float64
 53  avg_negative_polarity          39644 non-null  float64
 54  min_negative_polarity          39644 non-null  float64
 55  max_negative_polarity          39644 non-null  float64
 56  title_subjectivity             39644 non-null  float64
 57  title_sentiment_polarity       39644 non-null  float64
 58  abs_title_subjectivity         39644 non-null  float64
 59  abs_title_sentiment_polarity   39644 non-null  float64
 60  shares                         39644 non-null  int64
dtypes: float64(59), int64(1), object(1)
memory usage: 18.5+ MB

In [3]:
df.columns = df.columns.str.strip()

df.columns

Index(['url', 'timedelta', 'n_tokens_title', 'n_tokens_content',
       'n_unique_tokens', 'n_non_stop_words', 'n_non_stop_unique_tokens',
       'num_hrefs', 'num_self_hrefs', 'num_imgs', 'num_videos',
       'average_token_length', 'num_keywords', 'data_channel_is_lifestyle',
       'data_channel_is_entertainment', 'data_channel_is_bus',
       'data_channel_is_socmed', 'data_channel_is_tech',
       'data_channel_is_world', 'kw_min_min', 'kw_max_min', 'kw_avg_min',
       'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
       'kw_avg_avg', 'self_reference_min_shares', 'self_reference_max_shares',
       'self_reference_avg_sharess', 'weekday_is_monday', 'weekday_is_tuesday',
       'weekday_is_wednesday', 'weekday_is_thursday', 'weekday_is_friday',
       'weekday_is_saturday', 'weekday_is_sunday', 'is_weekend', 'LDA_00',
       'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04', 'global_subjectivity',
       'global_sentiment_polarity', 'global_rate_positive_words',
       'global_rate_negative_words', 'rate_positive_words',
       'rate_negative_words', 'avg_positive_polarity', 'min_positive_polarity',
       'max_positive_polarity', 'avg_negative_polarity',
       'min_negative_polarity', 'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'shares'],
      dtype='object')

In [6]:
# Drop unnecessary columns
df.drop(columns=["url", "timedelta"], inplace=True)

In [7]:
# Check for missing values
df.isnull().sum()

n_tokens_title                   0
n_tokens_content                 0
n_unique_tokens                  0
n_non_stop_words                 0
n_non_stop_unique_tokens         0
num_hrefs                        0
num_self_hrefs                   0
num_imgs                         0
num_videos                       0
average_token_length             0
num_keywords                     0
data_channel_is_lifestyle        0
data_channel_is_entertainment    0
data_channel_is_bus              0
data_channel_is_socmed           0
data_channel_is_tech             0
data_channel_is_world            0
kw_min_min                       0
kw_max_min                       0
kw_avg_min                       0
kw_min_max                       0
kw_max_max                       0
kw_avg_max                       0
kw_min_avg                       0
kw_max_avg                       0
kw_avg_avg                       0
self_reference_min_shares        0
self_reference_max_shares        0
self_reference_avg_sharess       0
weekday_is_monday                0
weekday_is_tuesday               0
weekday_is_wednesday             0
weekday_is_thursday              0
weekday_is_friday                0
weekday_is_saturday              0
weekday_is_sunday                0
is_weekend                       0
LDA_00                           0
LDA_01                           0
LDA_02                           0
LDA_03                           0
LDA_04                           0
global_subjectivity              0
global_sentiment_polarity        0
global_rate_positive_words       0
global_rate_negative_words       0
rate_positive_words              0
rate_negative_words              0
avg_positive_polarity            0
min_positive_polarity            0
max_positive_polarity            0
avg_negative_polarity            0
min_negative_polarity            0
max_negative_polarity            0
title_subjectivity               0
title_sentiment_polarity         0
abs_title_subjectivity           0
abs_title_sentiment_polarity     0
shares                           0
dtype: int64

In [8]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
# Create log-transformed target
df["log_shares"] = np.log1p(df["shares"])

In [10]:
# Quick Summary Stats
df.describe()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares,log_shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,4.548239,...,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184,7.475692
std,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,0.844406,...,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749,0.929674
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000,0.693147
25%,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,4.478404,...,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000,6.853299
50%,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,4.664082,...,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000,7.244942
75%,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,4.854839,...,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000,7.937732
max,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,8.041534,...,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000,13.645079

In [12]:
# Save cleaned data
df.to_csv("../data/processed/cleaned_online_news.csv", index=False)